name: "Docker"

on:
  workflow_dispatch:

  push:
    branches: ["master"]

  schedule:
    - cron: "0 8 * * 1"

jobs:
  build:
    name: "Build"
    uses: dockette/.github/.github/workflows/docker.yml@master
    secrets: inherit
    with:
        image: "dockette/dbdump"
        tag: "${{ matrix.item }}"
        context: "${{ matrix.item }}"
    strategy:
      matrix:
        include:
          - item: mariadb-10-2
          - item: mariadb-10-4
          - item: mariadb-10-6
          - item: mariadb-10-11
          - item: mariadb-11-1
          - item: mariadb-11-2
          - item: mariadb-11-4
          - item: mariadb-11-5
          - item: mariadb-11-7
          - item: mariadb-11-8

      fail-fast: false
